export * from './h'
export * from './createVNode'
export * from './renderer'
export * from './apiLifeCycle'
export { getCurrentInstance } from './component'
export { provide, inject } from './apiInject'
export { Teleport, isTeleport } from './Teleport'
