export * from './h'
export * from './createVNode'
export * from './renderer'
export * from './apiLifeCycle'
export { getCurrentInstance } from './component'
export { provide, inject } from './apiInject'
export { Teleport, isTeleport } from './Teleport'
export { KeepAlive, isKeepAlive } from './KeepAlive'
export { defineComponent } from './defineComponent'
export { defineAsyncComponent } from './defineAsyncComponent'
